### PR TITLE
Add preliminary Swift Syntax HighLighting

### PR DESCRIPTION
**Pull request by naclcaleb**
This was created due to #8

### CODE REVIEW

**Comment by naclcaleb** [comment]
I realize I forgot to add any `tmPreferences` files for this, as well as `Default.sublime-keymap` or a `sublime-build` file, since none of those were included in the repo the files were retrieved from: https://github.com/GregoryBL/SwiftSyntax

**Comment by cmyr** [comment]
So not having `sublime-keymap` is fine, since we don't really expect to use it. The missing `tmPreferences` is more of a concern, since we depend on them for auto-indent and comment toggling, which are pretty important for language support.

It's also not great that the syntax is three years old, although I'm not sure exactly what will be missing; does `do-try-catch` get highlighted correctly with this syntax, for instance? How about visibility modifiers?

I'd be curious for @mmatoszko's opinion, here: he looked into this a little while ago iirc.

**Comment by naclcaleb** [comment]
I'll keep working on it. I might need to find a newer sublime-syntax.

**Comment by naclcaleb** [comment]
I found this, which uses `tmLanguage`. 
Does this need to be converted to a `sublime-syntax` file?

https://github.com/quiqueg/Swift-Sublime-Package

**Comment by cmyr** [comment]
We can load either `tmLanguage` or `sublime-syntax`. I'm not sure if there's a preference? The place to check would be the docs for [syntect](https://github.com/trishume/syntect) which is the library that handles this stuff.

**Comment by MatthiasSaihttam** [comment]
I wasn’t successful in my early testing when using `.tmLanguage` files; I’ve been converting them with the `sublime_syntax_convertor` gem. (I also have Swift syntax working locally; I was planning on PRing soon.)

**Comment by naclcaleb** [comment]
Ok, I'll leave that to you then

**Comment by cmyr** [comment]
Okay cool, thanks for the info @MatthiasSaihttam and thanks for the PR @naclcaleb!

**Comment by naclcaleb** [comment]
Welcome!
Sorry I wasn't very much help. I don't actually use xi-editor. I tried installing it a couple times, but I get an error about it not supporting Swift 5.

And in general I use Vim and VSCode.

**Pull request closed without merging**
